spring:
  profiles:
    active:
      - dev


logging:
  level:
    com.example.springboot: info

url:
  orderUrl: http://localhost:8081/orderCenter
  userUrl: http://localhost:8020/userCenter
  triageUrl: http://localhost:8030/triageCenter

